# Day 4 – Pandas Basics

## Objective

Learn how to use Pandas for data manipulation, CSV handling, and basic analysis.

---

In [1]:
import pandas as pd


print(pd.__version__)

3.0.5

In [2]:
#Data Structures in pandas in python 

# 1).Series data structure
     
x=[1,2,3,4,5,6,7,8,9]    #using list
var=pd.Series(x)

print(var)
print(type(var))

#access values by index
print(var[1:5])

#changing index values
var1=pd.Series(x,index=['a','b','c','d','e','f','g','h','i'])
print(var1)

dic={
    "name":["Anand","Vishal","Rahul"],
    "subject":["Python","Java","C++"],
    "Rank":[1,2,3]

}

var2=pd.Series(dic)
var2

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
<class 'pandas.Series'>
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
dtype: int64

name       [Anand, Vishal, Rahul]
subject       [Python, Java, C++]
Rank                    [1, 2, 3]
dtype: object

In [3]:
s=pd.Series(12)
s
#strectching data into multiple indexs
s1=pd.Series(12,index=[1,10])
s1

s2=pd.Series(12,index=[1,2,3,4,5,6])
s3=pd.Series(12,index=[1,2,3,4])
print(s2+s3)

1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
dtype: float64

In [4]:
py_list=[1,2,3,4,5,6,7,8,9]
var=pd.DataFrame(py_list)
print( var,type(var))

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8
8  9 <class 'pandas.DataFrame'>

In [5]:
dictionar={
    "a":[1,2,3,4,5,6]
    ,
    "b":[1,2,3,4,4,5]
    ,
    "c":[6,7,8,9,0,0]
    ,
    "d":[11,22,3,4,5,88]
}
var1=pd.DataFrame(dictionar)
print(var1,type(var1))

#specific column 
var2=pd.DataFrame(dictionar,columns=["a","d"])
print(var2,type(var2))

#access by index
var3=pd.DataFrame(dictionar)
print(var3)
print()
print(var3["a"][4])

   a  b  c   d
0  1  1  6  11
1  2  2  7  22
2  3  3  8   3
3  4  4  9   4
4  5  4  0   5
5  6  5  0  88 <class 'pandas.DataFrame'>
   a   d
0  1  11
1  2  22
2  3   3
3  4   4
4  5   5
5  6  88 <class 'pandas.DataFrame'>
   a  b  c   d
0  1  1  6  11
1  2  2  7  22
2  3  3  8   3
3  4  4  9   4
4  5  4  0   5
5  6  5  0  88

5

In [6]:
#using python list
py_list=[[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]]
var=pd.DataFrame(py_list)
print(var,type(var))

   0  1  2  3  4  5  6  7
0  1  2  3  4  5  6  7  8
1  1  2  3  4  5  6  7  8 <class 'pandas.DataFrame'>

In [7]:
#using python series
sr={
    "s":pd.Series([1,2,3,4,5]),"r":pd.Series([6,7,8,9,0])
}
var=pd.DataFrame(sr)
print(var,type(var))

   s  r
0  1  6
1  2  7
2  3  8
3  4  9
4  5  0 <class 'pandas.DataFrame'>

In [8]:
#Arithmetic operation on pyhton pandas
var=pd.DataFrame({"A":[1,2,3,4,5,6],"B":[7,8,9,1,2,3]})
print(f"{var}\n")
var["C"]=var["A"]+var["B"]
print(f"{var}\n")
var["C"]=var["A"]-var["B"]
print(f"{var}\n")
var["C"]=var["A"]*var["B"]
print(f"{var}\n")
var["C"]=var["A"]/var["B"]
print(f"{var}\n")

   A  B
0  1  7
1  2  8
2  3  9
3  4  1
4  5  2
5  6  3

   A  B   C
0  1  7   8
1  2  8  10
2  3  9  12
3  4  1   5
4  5  2   7
5  6  3   9

   A  B  C
0  1  7 -6
1  2  8 -6
2  3  9 -6
3  4  1  3
4  5  2  3
5  6  3  3

   A  B   C
0  1  7   7
1  2  8  16
2  3  9  27
3  4  1   4
4  5  2  10
5  6  3  18

   A  B         C
0  1  7  0.142857
1  2  8  0.250000
2  3  9  0.333333
3  4  1  4.000000
4  5  2  2.500000
5  6  3  2.000000

In [9]:
var1=pd.DataFrame({"A":[20,12,32,54,34],
                   "B":[45,22,55,21,11]})
var1["Result"]=var1["A"]<=20
var1

    A   B  Result
0  20  45    True
1  12  22    True
2  32  55   False
3  54  21   False
4  34  11   False

In [10]:
#Insert
var=pd.DataFrame({"A":[1,2,3,4,5],"B":[11,22,33,44,55]
                  ,"C":[111,222,333,444,555]})
var
var.insert(1,"A_1",[1.1,2.2,3.3,4.4,5.5])
var

var["D"]=var["A"][:3]
var

   A  A_1   B    C    D
0  1  1.1  11  111  1.0
1  2  2.2  22  222  2.0
2  3  3.3  33  333  3.0
3  4  4.4  44  444  NaN
4  5  5.5  55  555  NaN

In [11]:
var=pd.DataFrame({"A":[1,2,3,4,5],"B":[11,22,33,44,55]
                  ,"C":[111,222,333,444,555]})
var1=var.pop("B")

print(f"Deleted Valus: \n{var1}")
print(f"Updated Values: \n{var}")

Deleted Valus:
0    11
1    22
2    33
3    44
4    55
Name: B, dtype: int64
Updated Values:
   A    C
0  1  111
1  2  222
2  3  333
3  4  444
4  5  555

In [12]:
#Create Csv file
var=pd.DataFrame({"A":[1,2,3,4,5],"B":[11,22,33,44,55]
                  ,"C":[111,222,333,444,555]})
print(var)

var.to_csv("Test.csv")
#to remove index from CSV file
var.to_csv("Test_Without_Index.csv",index=False)
#to change headers
var.to_csv("Test_changed_header.csv",header=["AA","BB","CC"])
var

   A   B    C
0  1  11  111
1  2  22  222
2  3  33  333
3  4  44  444
4  5  55  555

   A   B    C
0  1  11  111
1  2  22  222
2  3  33  333
3  4  44  444
4  5  55  555

In [13]:
#Read CSV files
csv_1=pd.read_csv("student_scores.csv")
print(csv_1)
csv_2=pd.read_csv("student_scores.csv", nrows=1) # print number of rows want
print(csv_2)
csv_3=pd.read_csv("student_scores.csv", usecols=["Math"]) #single column print
print(csv_3)
csv_4=pd.read_csv("student_scores.csv", usecols=[4,3]) #multiple columns print
print(csv_4)
csv_5=pd.read_csv("student_scores.csv", skiprows=[1]) #single row skip
print(csv_5)
csv_6=pd.read_csv("student_scores.csv", skiprows=[3,6,8]) #multiple skipping rows
print(csv_6)
csv_7=pd.read_csv("student_scores.csv", index_col=["Attendance"]) #change the inex with the any column
print(csv_7)
csv_8=pd.read_csv("student_scores.csv", header=3) #change the header to any row of the csv file
print(csv_8)
csv_9=pd.read_csv("student_scores.csv", names=["Student_Score"])
print(csv_9)
csv_10=pd.read_csv("student_scores.csv", names=["ID","NAME","MATH","SCIENCE","ENGLISH","ATTENDEANCE"])
print(csv_10)

   Student_ID     Name  Math  Science  English  Attendance
0         101    Alice    85       90       88          95
1         102      Bob    78       82       80          90
2         103  Charlie    92       89       94          98
3         104    David    70       75       72          85
4         105      Eva    88       91       90          97
5         106    Frank    65       68       70          80
6         107    Grace    95       94       96          99
7         108    Henry    80       78       82          88
8         109      Ivy    90       93       89          96
9         110     Jack    76       74       78          84
   Student_ID   Name  Math  Science  English  Attendance
0         101  Alice    85       90       88          95
   Math
0    85
1    78
2    92
3    70
4    88
5    65
6    95
7    80
8    90
9    76
   Science  English
0       90       88
1       82       80
2       89       94
3       75       72
4       91       90
5       68       70
6       94       96
7       78       82
8       93       89
9       74       78
   Student_ID     Name  Math  Science  English  Attendance
0         102      Bob    78       82       80          90
1         103  Charlie    92       89       94          98
2         104    David    70       75       72          85
3         105      Eva    88       91       90          97
4         106    Frank    65       68       70          80
5         107    Grace    95       94       96          99
6         108    Henry    80       78       82          88
7         109      Ivy    90       93       89          96
8         110     Jack    76       74       78          84
   Student_ID   Name  Math  Science  English  Attendance
0         101  Alice    85       90       88          95
1         102    Bob    78       82       80          90
2         104  David    70       75       72          85
3         105    Eva    88       91       90          97
4         107  Grace    95       94       96          99
5         109    Ivy    90       93       89          96
6         110   Jack    76       74       78          84
            Student_ID     Name  Math  Science  English
Attendance
95                 101    Alice    85       90       88
90                 102      Bob    78       82       80
98                 103  Charlie    92       89       94
85                 104    David    70       75       72
97                 105      Eva    88       91       90
80                 106    Frank    65       68       70
99                 107    Grace    95       94       96
88                 108    Henry    80       78       82
96                 109      Ivy    90       93       89
84                 110     Jack    76       74       78
   103 Charlie  92  89  94  98
0  104   David  70  75  72  85
1  105     Eva  88  91  90  97
2  106   Frank  65  68  70  80
3  107   Grace  95  94  96  99
4  108   Henry  80  78  82  88
5  109     Ivy  90  93  89  96
6  110    Jack  76  74  78  84
                                        Student_Score
Student_ID Name    Math Science English    Attendance
101        Alice   85   90      88                 95
102        Bob     78   82      80                 90
103        Charlie 92   89      94                 98
104        David   70   75      72                 85
105        Eva     88   91      90                 97
106        Frank   65   68      70                 80
107        Grace   95   94      96                 99
108        Henry   80   78      82                 88
109        Ivy     90   93      89                 96
110        Jack    76   74      78                 84
            ID     NAME  MATH  SCIENCE  ENGLISH ATTENDEANCE
0   Student_ID     Name  Math  Science  English  Attendance
1          101    Alice    85       90       88          95
2          102      Bob    78       82       80          90
3          103  Charlie    92       89       94          98
4          104    David    70       75       72          85
5          105      Eva    88       91       90          97
6          106    Frank    65       68       70          80
7          107    Grace    95       94       96          99
8          108    Henry    80       78       82          88
9          109      Ivy    90       93       89          96
10         110     Jack    76       74       78          84

In [14]:
csv_1=pd.read_csv("student_scores.csv")
# print(csv_1)
csv_2=pd.read_csv("student_scores.csv",dtype={"Math":"float","Science":"float","English":"float"} )
print(csv_2)

   Student_ID     Name  Math  Science  English  Attendance
0         101    Alice  85.0     90.0     88.0          95
1         102      Bob  78.0     82.0     80.0          90
2         103  Charlie  92.0     89.0     94.0          98
3         104    David  70.0     75.0     72.0          85
4         105      Eva  88.0     91.0     90.0          97
5         106    Frank  65.0     68.0     70.0          80
6         107    Grace  95.0     94.0     96.0          99
7         108    Henry  80.0     78.0     82.0          88
8         109      Ivy  90.0     93.0     89.0          96
9         110     Jack  76.0     74.0     78.0          84

In [15]:
#pandas function
csv_1=pd.read_csv("student_scores.csv")
print(csv_1.index) #print range of index
print(csv_1.columns) #print all columns name
print(csv_1.describe()) # numerical columns calculate [count,mean,std,min,max etc]
#get data
print(csv_1.head()) #first 5 rows
print(csv_1.head(2))

print(csv_1.tail()) #last 5 rows
print(csv_1.tail(2))
print()
print(csv_1[:2]) # slicing
print(csv_1[2:5]) #

print(csv_1.index.array) #index into array
import numpy as np
print(csv_1.to_numpy) #csv_1 into numpy
v=np.asarray(csv_1) #csv_1 into numpy
print("Helo")
csv_1.sort_index(axis=0,ascending=False) 
#csv_1["Name"][0]="Anand"

RangeIndex(start=0, stop=10, step=1)
Index(['Student_ID', 'Name', 'Math', 'Science', 'English', 'Attendance'], dtype='str')
       Student_ID       Math    Science    English  Attendance
count    10.00000  10.000000  10.000000  10.000000   10.000000
mean    105.50000  81.900000  83.400000  83.900000   91.200000
std       3.02765   9.814389   9.215928   8.924996    6.713171
min     101.00000  65.000000  68.000000  70.000000   80.000000
25%     103.25000  76.500000  75.750000  78.500000   85.750000
50%     105.50000  82.500000  85.500000  85.000000   92.500000
75%     107.75000  89.500000  90.750000  89.750000   96.750000
max     110.00000  95.000000  94.000000  96.000000   99.000000
   Student_ID     Name  Math  Science  English  Attendance
0         101    Alice    85       90       88          95
1         102      Bob    78       82       80          90
2         103  Charlie    92       89       94          98
3         104    David    70       75       72          85
4         105      Eva    88       91       90          97
   Student_ID   Name  Math  Science  English  Attendance
0         101  Alice    85       90       88          95
1         102    Bob    78       82       80          90
   Student_ID   Name  Math  Science  English  Attendance
5         106  Frank    65       68       70          80
6         107  Grace    95       94       96          99
7         108  Henry    80       78       82          88
8         109    Ivy    90       93       89          96
9         110   Jack    76       74       78          84
   Student_ID  Name  Math  Science  English  Attendance
8         109   Ivy    90       93       89          96
9         110  Jack    76       74       78          84

   Student_ID   Name  Math  Science  English  Attendance
0         101  Alice    85       90       88          95
1         102    Bob    78       82       80          90
   Student_ID     Name  Math  Science  English  Attendance
2         103  Charlie    92       89       94          98
3         104    David    70       75       72          85
4         105      Eva    88       91       90          97
<NumpyExtensionArray>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Length: 10, dtype: int64
<bound method DataFrame.to_numpy of    Student_ID     Name  Math  Science  English  Attendance
0         101    Alice    85       90       88          95
1         102      Bob    78       82       80          90
2         103  Charlie    92       89       94          98
3         104    David    70       75       72          85
4         105      Eva    88       91       90          97
5         106    Frank    65       68       70          80
6         107    Grace    95       94       96          99
7         108    Henry    80       78       82          88
8         109      Ivy    90       93       89          96
9         110     Jack    76       74       78          84>
Helo

   Student_ID     Name  Math  Science  English  Attendance
9         110     Jack    76       74       78          84
8         109      Ivy    90       93       89          96
7         108    Henry    80       78       82          88
6         107    Grace    95       94       96          99
5         106    Frank    65       68       70          80
4         105      Eva    88       91       90          97
3         104    David    70       75       72          85
2         103  Charlie    92       89       94          98
1         102      Bob    78       82       80          90
0         101    Alice    85       90       88          95

In [16]:
#Access elements & Rows & Columns
csv_1=pd.read_csv("student_scores.csv")
print(csv_1.loc[:,["Math","Science"]])
print(csv_1.loc[[2,3],:])
print(csv_1.iloc[0,3])
print(csv_1.drop("English",axis=1))
print(csv_1.drop(8,axis=0))

   Math  Science
0    85       90
1    78       82
2    92       89
3    70       75
4    88       91
5    65       68
6    95       94
7    80       78
8    90       93
9    76       74
   Student_ID     Name  Math  Science  English  Attendance
2         103  Charlie    92       89       94          98
3         104    David    70       75       72          85
90
   Student_ID     Name  Math  Science  Attendance
0         101    Alice    85       90          95
1         102      Bob    78       82          90
2         103  Charlie    92       89          98
3         104    David    70       75          85
4         105      Eva    88       91          97
5         106    Frank    65       68          80
6         107    Grace    95       94          99
7         108    Henry    80       78          88
8         109      Ivy    90       93          96
9         110     Jack    76       74          84
   Student_ID     Name  Math  Science  English  Attendance
0         101    Alice    85       90       88          95
1         102      Bob    78       82       80          90
2         103  Charlie    92       89       94          98
3         104    David    70       75       72          85
4         105      Eva    88       91       90          97
5         106    Frank    65       68       70          80
6         107    Grace    95       94       96          99
7         108    Henry    80       78       82          88
9         110     Jack    76       74       78          84

In [17]:
# import pandas as pd
csv=pd.read_csv("handle.csv")
print(csv)

#dropna

print(csv.dropna()) # it delete the rows which have Nan
print(csv.dropna(axis=1)) # it delete the columns which have Nan

print(csv.dropna(how="any")) # it drops the rows which have Nan in any column
print(csv.dropna(how="all")) # it drops the rows which have Nan in all columns

print(csv.dropna(subset=["Department"])) #it drops the rows which have Nan in Department column

print(csv.dropna(inplace=True)) # reove rows which have Nan
print(csv.dropna(thresh=2))

    EmployeeID          Name   Age   Department   Salary    JoinDate  \
0          101   Ravi Sharma  29.0  Engineering  55000.0  15-03-2019
1          102   Priya Patel   NaN    Marketing  48000.0  01-06-2020
2          103    Aman Gupta  35.0  Engineering      NaN  23-11-2018
3          104    Neha Singh  41.0          NaN  62000.0  10-01-2017
4          105           NaN  28.0        Sales  39000.0  05-09-2021
5          106   Karan Mehta  33.0  Engineering  58000.0         NaN
6          107   Sneha Joshi  26.0    Marketing  45000.0  14-02-2022
7          108    Vikram Rao   NaN        Sales  41000.0  19-07-2020
8          109  Anjali Desai  38.0      Finance  67000.0  30-05-2016
9          110   Rohit Verma  31.0          NaN  53000.0  08-08-2019
10         111    Meera Iyer  45.0      Finance      NaN  01-12-2015
11         112           NaN   NaN          NaN      NaN         NaN
12         113  Sanjay Kumar  27.0        Sales      NaN  17-04-2021
13         114    Divya Nair   NaN  Engineering  60000.0  25-10-2018
14         115   Arjun Reddy  36.0    Marketing  49000.0         NaN
15         116    Pooja Shah  30.0      Finance  64000.0  12-06-2019

    PerformanceScore       City
0                4.2  Ahmedabad
1                3.8      Surat
2                4.5        NaN
3                NaN   Vadodara
4                3.1     Rajkot
5                4.0  Ahmedabad
6                NaN      Surat
7                3.6        NaN
8                4.3   Vadodara
9                3.9  Ahmedabad
10               4.7     Rajkot
11               NaN        NaN
12               3.3      Surat
13               NaN  Ahmedabad
14               3.5   Vadodara
15               4.1        NaN
   EmployeeID          Name   Age   Department   Salary    JoinDate  \
0         101   Ravi Sharma  29.0  Engineering  55000.0  15-03-2019
8         109  Anjali Desai  38.0      Finance  67000.0  30-05-2016

   PerformanceScore       City
0               4.2  Ahmedabad
8               4.3   Vadodara
    EmployeeID
0          101
1          102
2          103
3          104
4          105
5          106
6          107
7          108
8          109
9          110
10         111
11         112
12         113
13         114
14         115
15         116
   EmployeeID          Name   Age   Department   Salary    JoinDate  \
0         101   Ravi Sharma  29.0  Engineering  55000.0  15-03-2019
8         109  Anjali Desai  38.0      Finance  67000.0  30-05-2016

   PerformanceScore       City
0               4.2  Ahmedabad
8               4.3   Vadodara
    EmployeeID          Name   Age   Department   Salary    JoinDate  \
0          101   Ravi Sharma  29.0  Engineering  55000.0  15-03-2019
1          102   Priya Patel   NaN    Marketing  48000.0  01-06-2020
2          103    Aman Gupta  35.0  Engineering      NaN  23-11-2018
3          104    Neha Singh  41.0          NaN  62000.0  10-01-2017
4          105           NaN  28.0        Sales  39000.0  05-09-2021
5          106   Karan Mehta  33.0  Engineering  58000.0         NaN
6          107   Sneha Joshi  26.0    Marketing  45000.0  14-02-2022
7          108    Vikram Rao   NaN        Sales  41000.0  19-07-2020
8          109  Anjali Desai  38.0      Finance  67000.0  30-05-2016
9          110   Rohit Verma  31.0          NaN  53000.0  08-08-2019
10         111    Meera Iyer  45.0      Finance      NaN  01-12-2015
11         112           NaN   NaN          NaN      NaN         NaN
12         113  Sanjay Kumar  27.0        Sales      NaN  17-04-2021
13         114    Divya Nair   NaN  Engineering  60000.0  25-10-2018
14         115   Arjun Reddy  36.0    Marketing  49000.0         NaN
15         116    Pooja Shah  30.0      Finance  64000.0  12-06-2019

    PerformanceScore       City
0                4.2  Ahmedabad
1                3.8      Surat
2                4.5        NaN
3                NaN   Vadodara
4                3.1     Rajkot
5                4.0  Ahmedabad
6                NaN      Surat
7                3.6        NaN
8                4.3   Vadodara
9                3.9  Ahmedabad
10               4.7     Rajkot
11               NaN        NaN
12               3.3      Surat
13               NaN  Ahmedabad
14               3.5   Vadodara
15               4.1        NaN
    EmployeeID          Name   Age   Department   Salary    JoinDate  \
0          101   Ravi Sharma  29.0  Engineering  55000.0  15-03-2019
1          102   Priya Patel   NaN    Marketing  48000.0  01-06-2020
2          103    Aman Gupta  35.0  Engineering      NaN  23-11-2018
4          105           NaN  28.0        Sales  39000.0  05-09-2021
5          106   Karan Mehta  33.0  Engineering  58000.0         NaN
6          107   Sneha Joshi  26.0    Marketing  45000.0  14-02-2022
7          108    Vikram Rao   NaN        Sales  41000.0  19-07-2020
8          109  Anjali Desai  38.0      Finance  67000.0  30-05-2016
10         111    Meera Iyer  45.0      Finance      NaN  01-12-2015
12         113  Sanjay Kumar  27.0        Sales      NaN  17-04-2021
13         114    Divya Nair   NaN  Engineering  60000.0  25-10-2018
14         115   Arjun Reddy  36.0    Marketing  49000.0         NaN
15         116    Pooja Shah  30.0      Finance  64000.0  12-06-2019

    PerformanceScore       City
0                4.2  Ahmedabad
1                3.8      Surat
2                4.5        NaN
4                3.1     Rajkot
5                4.0  Ahmedabad
6                NaN      Surat
7                3.6        NaN
8                4.3   Vadodara
10               4.7     Rajkot
12               3.3      Surat
13               NaN  Ahmedabad
14               3.5   Vadodara
15               4.1        NaN
None
   EmployeeID          Name   Age   Department   Salary    JoinDate  \
0         101   Ravi Sharma  29.0  Engineering  55000.0  15-03-2019
8         109  Anjali Desai  38.0      Finance  67000.0  30-05-2016

   PerformanceScore       City
0               4.2  Ahmedabad
8               4.3   Vadodara

In [18]:
csv=pd.read_csv("handle.csv")
print(csv)

# fillna

print(csv.fillna({"City":"Silvass", "Salary":20000}))

print(csv.ffill())
print(csv.ffill(axis=1))

print(csv.bfill())
print(csv.bfill(axis=1))

    EmployeeID          Name   Age   Department   Salary    JoinDate  \
0          101   Ravi Sharma  29.0  Engineering  55000.0  15-03-2019
1          102   Priya Patel   NaN    Marketing  48000.0  01-06-2020
2          103    Aman Gupta  35.0  Engineering      NaN  23-11-2018
3          104    Neha Singh  41.0          NaN  62000.0  10-01-2017
4          105           NaN  28.0        Sales  39000.0  05-09-2021
5          106   Karan Mehta  33.0  Engineering  58000.0         NaN
6          107   Sneha Joshi  26.0    Marketing  45000.0  14-02-2022
7          108    Vikram Rao   NaN        Sales  41000.0  19-07-2020
8          109  Anjali Desai  38.0      Finance  67000.0  30-05-2016
9          110   Rohit Verma  31.0          NaN  53000.0  08-08-2019
10         111    Meera Iyer  45.0      Finance      NaN  01-12-2015
11         112           NaN   NaN          NaN      NaN         NaN
12         113  Sanjay Kumar  27.0        Sales      NaN  17-04-2021
13         114    Divya Nair   NaN  Engineering  60000.0  25-10-2018
14         115   Arjun Reddy  36.0    Marketing  49000.0         NaN
15         116    Pooja Shah  30.0      Finance  64000.0  12-06-2019

    PerformanceScore       City
0                4.2  Ahmedabad
1                3.8      Surat
2                4.5        NaN
3                NaN   Vadodara
4                3.1     Rajkot
5                4.0  Ahmedabad
6                NaN      Surat
7                3.6        NaN
8                4.3   Vadodara
9                3.9  Ahmedabad
10               4.7     Rajkot
11               NaN        NaN
12               3.3      Surat
13               NaN  Ahmedabad
14               3.5   Vadodara
15               4.1        NaN
    EmployeeID          Name   Age   Department   Salary    JoinDate  \
0          101   Ravi Sharma  29.0  Engineering  55000.0  15-03-2019
1          102   Priya Patel   NaN    Marketing  48000.0  01-06-2020
2          103    Aman Gupta  35.0  Engineering  20000.0  23-11-2018
3          104    Neha Singh  41.0          NaN  62000.0  10-01-2017
4          105           NaN  28.0        Sales  39000.0  05-09-2021
5          106   Karan Mehta  33.0  Engineering  58000.0         NaN
6          107   Sneha Joshi  26.0    Marketing  45000.0  14-02-2022
7          108    Vikram Rao   NaN        Sales  41000.0  19-07-2020
8          109  Anjali Desai  38.0      Finance  67000.0  30-05-2016
9          110   Rohit Verma  31.0          NaN  53000.0  08-08-2019
10         111    Meera Iyer  45.0      Finance  20000.0  01-12-2015
11         112           NaN   NaN          NaN  20000.0         NaN
12         113  Sanjay Kumar  27.0        Sales  20000.0  17-04-2021
13         114    Divya Nair   NaN  Engineering  60000.0  25-10-2018
14         115   Arjun Reddy  36.0    Marketing  49000.0         NaN
15         116    Pooja Shah  30.0      Finance  64000.0  12-06-2019

    PerformanceScore       City
0                4.2  Ahmedabad
1                3.8      Surat
2                4.5    Silvass
3                NaN   Vadodara
4                3.1     Rajkot
5                4.0  Ahmedabad
6                NaN      Surat
7                3.6    Silvass
8                4.3   Vadodara
9                3.9  Ahmedabad
10               4.7     Rajkot
11               NaN    Silvass
12               3.3      Surat
13               NaN  Ahmedabad
14               3.5   Vadodara
15               4.1    Silvass
    EmployeeID          Name   Age   Department   Salary    JoinDate  \
0          101   Ravi Sharma  29.0  Engineering  55000.0  15-03-2019
1          102   Priya Patel  29.0    Marketing  48000.0  01-06-2020
2          103    Aman Gupta  35.0  Engineering  48000.0  23-11-2018
3          104    Neha Singh  41.0  Engineering  62000.0  10-01-2017
4          105    Neha Singh  28.0        Sales  39000.0  05-09-2021
5          106   Karan Mehta  33.0  Engineering  58000.0  05-09-2021
6          107   Sneha Joshi  26.0    Marketing  45000.0  14-02-2022
7          108    Vikram Rao  26.0        Sales  41000.0  19-07-2020
8          109  Anjali Desai  38.0      Finance  67000.0  30-05-2016
9          110   Rohit Verma  31.0      Finance  53000.0  08-08-2019
10         111    Meera Iyer  45.0      Finance  53000.0  01-12-2015
11         112    Meera Iyer  45.0      Finance  53000.0  01-12-2015
12         113  Sanjay Kumar  27.0        Sales  53000.0  17-04-2021
13         114    Divya Nair  27.0  Engineering  60000.0  25-10-2018
14         115   Arjun Reddy  36.0    Marketing  49000.0  25-10-2018
15         116    Pooja Shah  30.0      Finance  64000.0  12-06-2019

    PerformanceScore       City
0                4.2  Ahmedabad
1                3.8      Surat
2                4.5      Surat
3                4.5   Vadodara
4                3.1     Rajkot
5                4.0  Ahmedabad
6                4.0      Surat
7                3.6      Surat
8                4.3   Vadodara
9                3.9  Ahmedabad
10               4.7     Rajkot
11               4.7     Rajkot
12               3.3      Surat
13               3.3  Ahmedabad
14               3.5   Vadodara
15               4.1   Vadodara
   EmployeeID          Name          Age   Department       Salary  \
0         101   Ravi Sharma         29.0  Engineering      55000.0
1         102   Priya Patel  Priya Patel    Marketing      48000.0
2         103    Aman Gupta         35.0  Engineering  Engineering
3         104    Neha Singh         41.0         41.0      62000.0
4         105           105         28.0        Sales      39000.0
5         106   Karan Mehta         33.0  Engineering      58000.0
6         107   Sneha Joshi         26.0    Marketing      45000.0
7         108    Vikram Rao   Vikram Rao        Sales      41000.0
8         109  Anjali Desai         38.0      Finance      67000.0
9         110   Rohit Verma         31.0         31.0      53000.0
10        111    Meera Iyer         45.0      Finance      Finance
11        112           112          112          112          112
12        113  Sanjay Kumar         27.0        Sales        Sales
13        114    Divya Nair   Divya Nair  Engineering      60000.0
14        115   Arjun Reddy         36.0    Marketing      49000.0
15        116    Pooja Shah         30.0      Finance      64000.0

      JoinDate PerformanceScore       City
0   15-03-2019              4.2  Ahmedabad
1   01-06-2020              3.8      Surat
2   23-11-2018              4.5        4.5
3   10-01-2017       10-01-2017   Vadodara
4   05-09-2021              3.1     Rajkot
5      58000.0              4.0  Ahmedabad
6   14-02-2022       14-02-2022      Surat
7   19-07-2020              3.6        3.6
8   30-05-2016              4.3   Vadodara
9   08-08-2019              3.9  Ahmedabad
10  01-12-2015              4.7     Rajkot
11         112              112        112
12  17-04-2021              3.3      Surat
13  25-10-2018       25-10-2018  Ahmedabad
14     49000.0              3.5   Vadodara
15  12-06-2019              4.1        4.1
    EmployeeID          Name   Age   Department   Salary    JoinDate  \
0          101   Ravi Sharma  29.0  Engineering  55000.0  15-03-2019
1          102   Priya Patel  35.0    Marketing  48000.0  01-06-2020
2          103    Aman Gupta  35.0  Engineering  62000.0  23-11-2018
3          104    Neha Singh  41.0        Sales  62000.0  10-01-2017
4          105   Karan Mehta  28.0        Sales  39000.0  05-09-2021
5          106   Karan Mehta  33.0  Engineering  58000.0  14-02-2022
6          107   Sneha Joshi  26.0    Marketing  45000.0  14-02-2022
7          108    Vikram Rao  38.0        Sales  41000.0  19-07-2020
8          109  Anjali Desai  38.0      Finance  67000.0  30-05-2016
9          110   Rohit Verma  31.0      Finance  53000.0  08-08-2019
10         111    Meera Iyer  45.0      Finance  60000.0  01-12-2015
11         112  Sanjay Kumar  27.0        Sales  60000.0  17-04-2021
12         113  Sanjay Kumar  27.0        Sales  60000.0  17-04-2021
13         114    Divya Nair  36.0  Engineering  60000.0  25-10-2018
14         115   Arjun Reddy  36.0    Marketing  49000.0  12-06-2019
15         116    Pooja Shah  30.0      Finance  64000.0  12-06-2019

    PerformanceScore       City
0                4.2  Ahmedabad
1                3.8      Surat
2                4.5   Vadodara
3                3.1   Vadodara
4                3.1     Rajkot
5                4.0  Ahmedabad
6                3.6      Surat
7                3.6   Vadodara
8                4.3   Vadodara
9                3.9  Ahmedabad
10               4.7     Rajkot
11               3.3      Surat
12               3.3      Surat
13               3.5  Ahmedabad
14               3.5   Vadodara
15               4.1        NaN
   EmployeeID          Name          Age   Department      Salary    JoinDate  \
0         101   Ravi Sharma         29.0  Engineering     55000.0  15-03-2019
1         102   Priya Patel    Marketing    Marketing     48000.0  01-06-2020
2         103    Aman Gupta         35.0  Engineering  23-11-2018  23-11-2018
3         104    Neha Singh         41.0      62000.0     62000.0  10-01-2017
4         105          28.0         28.0        Sales     39000.0  05-09-2021
5         106   Karan Mehta         33.0  Engineering     58000.0         4.0
6         107   Sneha Joshi         26.0    Marketing     45000.0  14-02-2022
7         108    Vikram Rao        Sales        Sales     41000.0  19-07-2020
8         109  Anjali Desai         38.0      Finance     67000.0  30-05-2016
9         110   Rohit Verma         31.0      53000.0     53000.0  08-08-2019
10        111    Meera Iyer         45.0      Finance  01-12-2015  01-12-2015
11        112           NaN          NaN          NaN         NaN         NaN
12        113  Sanjay Kumar         27.0        Sales  17-04-2021  17-04-2021
13        114    Divya Nair  Engineering  Engineering     60000.0  25-10-2018
14        115   Arjun Reddy         36.0    Marketing     49000.0         3.5
15        116    Pooja Shah         30.0      Finance     64000.0  12-06-2019

   PerformanceScore       City
0               4.2  Ahmedabad
1               3.8      Surat
2               4.5        NaN
3          Vadodara   Vadodara
4               3.1     Rajkot
5               4.0  Ahmedabad
6             Surat      Surat
7               3.6        NaN
8               4.3   Vadodara
9               3.9  Ahmedabad
10              4.7     Rajkot
11              NaN        NaN
12              3.3      Surat
13        Ahmedabad  Ahmedabad
14              3.5   Vadodara
15              4.1        NaN

In [19]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
})

# Replace 'Alice' with 'Anna'
df['Name'] = df['Name'].replace('Alice', 'Anna')

print(df)

      Name  Age         City
0     Anna   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [20]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'C'],
    'Value1': [1, 2, 3, 4, 5],
    'Value2': [5, 4, 3, 2, 1]
}

df = pd.DataFrame(data)

# Group by 'Category' and calculate mean of 'Value1'
grouped_df = df.groupby('Category').mean()

print(grouped_df)

          Value1  Value2
Category
A            2.0     4.0
B            3.0     3.0
C            5.0     1.0

In [21]:

df1 = pd.DataFrame({
    'A': [1, 2],
    'B': [3, 4]
})

df2 = pd.DataFrame({
    'A': [5, 6],
    'B': [7, 8]
})

# Concatenate vertically
concat_df_vertical = pd.concat([df1, df2])

print(concat_df_vertical)

# Concatenate horizontally
concat_df_horizontal = pd.concat([df1, df2], axis=1)

print(concat_df_horizontal)

   A  B
0  1  3
1  2  4
0  5  7
1  6  8
   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [22]:

left_df = pd.DataFrame({
    'Key': ['A', 'B'],
    'Value1': [1, 2]
})

right_df = pd.DataFrame({
    'Key': ['A', 'C'],
    'Value2': [3, 4]
})

# Join on 'Key'
join_df = pd.merge(left_df, right_df, on='Key')

print(join_df)

  Key  Value1  Value2
0   A       1       3

In [23]:

data = {
    'Category': ['A', 'B', 'A', 'B', 'C'],
    'Subcategory': ['X', 'Y', 'Z', 'X', 'Y'],
    'Value': [1, 2, 3, 4, 5]
}

df = pd.DataFrame(data)

# Create a pivot table
pivot_table = df.pivot(index='Category', columns='Subcategory', values='Value')

print(pivot_table)

Subcategory    X    Y    Z
Category
A            1.0  NaN  3.0
B            4.0  2.0  NaN
C            NaN  5.0  NaN

In [24]:
data = {
    'Country': ['USA', 'Canada'],
    'Year2019': [100, 50],
    'Year2020': [110, 60]
}

df = pd.DataFrame(data)

# Melt the DataFrame
melted_df = df.melt(id_vars='Country', var_name='Year', value_name='Value')

print(melted_df)

  Country      Year  Value
0     USA  Year2019    100
1  Canada  Year2019     50
2     USA  Year2020    110
3  Canada  Year2020     60