# Day 9 – Predicting Score with ML

## Objective

Build a prediction pipeline for student scores using regression models.

---

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
data = pd.read_csv("student_scores_1.csv")

print(data)

        Name  Hours_Studied  Final_Score  Previous_Score  Attendance
0    STU_001            4.4         67.0            58.0        85.0
1    STU_002            9.6        100.0            97.0        96.0
2    STU_003            7.6         89.9            86.0        91.0
3    STU_004            6.4         74.8            69.0        83.0
4    STU_005            2.4         48.4            42.0        81.0
..       ...            ...          ...             ...         ...
497  STU_498            1.7         53.8             NaN        77.0
498  STU_499            9.8        100.0            99.0        91.0
499  STU_500            9.9        100.0            94.0        93.0
500  STU_021            6.5         73.0            65.0        88.0
501  STU_151            9.2         90.7            87.0        92.0

[502 rows x 5 columns]

In [3]:
data["Attendance"] = data["Attendance"].fillna(data["Attendance"].mean())
data["Previous_Score"] = data["Previous_Score"].fillna(data["Previous_Score"].mean())
data["Hours_Studied"] = data["Hours_Studied"].fillna(data["Hours_Studied"].mean())
data["Final_Score"] = data["Final_Score"].fillna(data["Final_Score"].mean())
print(data)

        Name  Hours_Studied  Final_Score  Previous_Score  Attendance
0    STU_001            4.4         67.0       58.000000        85.0
1    STU_002            9.6        100.0       97.000000        96.0
2    STU_003            7.6         89.9       86.000000        91.0
3    STU_004            6.4         74.8       69.000000        83.0
4    STU_005            2.4         48.4       42.000000        81.0
..       ...            ...          ...             ...         ...
497  STU_498            1.7         53.8       66.993902        77.0
498  STU_499            9.8        100.0       99.000000        91.0
499  STU_500            9.9        100.0       94.000000        93.0
500  STU_021            6.5         73.0       65.000000        88.0
501  STU_151            9.2         90.7       87.000000        92.0

[502 rows x 5 columns]

In [4]:
stored_data = data[
    [
        "Name",
        "Attendance",
        "Previous_Score",
        "Hours_Studied",
        "Final_Score"
    ]
].copy()

# Round all numeric values to 2 decimal places
stored_data = stored_data.round(2)

# Display
display(stored_data.head())

# Save with exactly 2 decimal places
stored_data.to_csv(
    "student_scores_cleaned.csv",
    index=False,
    float_format="%.2f"
)

print("Data stored successfully!")

      Name  Attendance  Previous_Score  Hours_Studied  Final_Score
0  STU_001        85.0            58.0            4.4         67.0
1  STU_002        96.0            97.0            9.6        100.0
2  STU_003        91.0            86.0            7.6         89.9
3  STU_004        83.0            69.0            6.4         74.8
4  STU_005        81.0            42.0            2.4         48.4

Data stored successfully!

In [5]:
X = data[["Hours_Studied", "Attendance", "Previous_Score"]]

y = data["Final_Score"]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [7]:
model = LinearRegression()

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [8]:
y_pred = model.predict(X_test)

comparison = pd.DataFrame({
    "Actual Score": y_test.values,
    "Predicted Score": y_pred.round(2)
})

comparison

     Actual Score  Predicted Score
0            76.9            73.54
1            83.5            83.57
2            73.2            75.34
3            52.2            54.79
4            95.0            97.19
..            ...              ...
96           77.5            77.00
97           85.3            85.25
98           57.1            57.31
99           51.7            53.94
100          65.1            61.58

[101 rows x 2 columns]

In [9]:
print("Mean Absolute Error : ", round(mean_absolute_error(y_test, y_pred),2))
print("Mean Squared Error : ", round(mean_squared_error(y_test, y_pred),2))
print("R² Score : ", round(r2_score(y_test, y_pred),2))

Mean Absolute Error :  2.08
Mean Squared Error :  6.33
R² Score :  0.98

In [10]:
new_student = pd.DataFrame({
    "Hours_Studied": [5],
    "Attendance": [85],
    "Previous_Score": [75]
})

prediction = model.predict(new_student)

print(f"Predicted Final Score: {prediction[0]:.2f}")

Predicted Final Score: 75.48

In [50]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

importance

          Feature  Coefficient
0   Hours_Studied     1.926573
1      Attendance     0.278702
2  Previous_Score     0.617353